language: go
go:
  - 1.13.15
  - tip
matrix:
  allow_failures:
    - go: tip

notifications:
  email:
    recipients: dean.karn@gmail.com
    on_success: change
    on_failure: always

before_install:
  - go get -u github.com/go-playground/overalls
  - go get -u github.com/mattn/goveralls
  - go get -u golang.org/x/tools/cmd/cover
  - mkdir -p $GOPATH/src/gopkg.in
  - ln -s $GOPATH/src/github.com/$TRAVIS_REPO_SLUG $GOPATH/src/gopkg.in/webhooks.v2
  - ln -s $GOPATH/src/github.com/$TRAVIS_REPO_SLUG $GOPATH/src/gopkg.in/webhooks.v3
  - ln -s $GOPATH/src/github.com/$TRAVIS_REPO_SLUG $GOPATH/src/gopkg.in/webhooks.v4
  - ln -s $GOPATH/src/github.com/$TRAVIS_REPO_SLUG $GOPATH/src/gopkg.in/webhooks.v5

before_script:
  - go get -t ./...

script:
  - make test

after_success: |
  [ $TRAVIS_GO_VERSION = 1.13.15 ] &&
  overalls -project="github.com/go-playground/webhooks" -covermode=count -ignore=.git,_examples,testdata -debug &&
  goveralls -coverprofile=overalls.coverprofile -service travis-ci -repotoken $COVERALLS_TOKEN
